[project]
name = "backend-py"
version = "0.1.0"
description = "Sample backend project developed with FastAPI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.11",
    "mypy>=1.15.0",
    "ruff>=0.10.0",
    "uvicorn>=0.34.0",
]
