name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV 
        uses: ./.github/actions/setup

      - name: Linting
        run: uvx ruff check .

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV 
        uses: ./.github/actions/setup

      - name: Formatting
        run: uvx ruff format .

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV 
        uses: ./.github/actions/setup

      - name: mypy
        run: uv run mypy .

  testing:
    name: Testing
    runs-on: ubuntu-latest
    needs: [linting, formatting, mypy]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV 
        uses: ./.github/actions/setup

      - name: Run tests
        run: uv run pytest .
      
  build:
    name: Building
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV 
        uses: ./.github/actions/setup

      - name: Build
        run: uv build .
